version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: wallnkap-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wallnkap-backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/wallnkap?authSource=admin
      - JWT_SECRET=your-super-secret-key
      - JWT_EXPIRATION=1d

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wallnkap-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongodb_data:
